name: Fourth Wf
on: 
  workflow_run:
    workflows: [First W]
    types:
      - completed
      

jobs:
  hello-f-c:
    runs-on: ubuntu-latest
    steps:
      - name: List Files 
        run: echo "hello"
