name: Third Wf
on: [push]

jobs:
  run-f-c:
    runs-on: ubuntu-latest
    steps:
      - name: List Files 
        run: ls -a
     # - uses: actions/checkout@v4
      - name: Copy Files
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$CITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: List Files
        run: ls -a

          