name: Third Wf
on: [push]

jobs:
  run-f-c:
    runs-on: ubuntu-latest
    steps:
      - name: List Files and Copy Repo
        run: ls -a
      - uses: actions/checkout@v4

      - name: List Files
        run: ls -a

          